version: '3.8'

services:
  
  postgres:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - aspnetcoreapp-network
  
  web:
    image: 'alexprotchenko/mailapi'
    container_name: 'mailapi'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    networks:
      - aspnetcoreapp-network


networks:
  aspnetcoreapp-network:
    driver: bridge